str1 = "hello my name is Aryan"
print(len(str1))
print(str1[:])
print(str1.capitalize())
print(str1.count("a"))
print(str1.upper())
print(str1.lower())
print(str1.isalpha())
print(str1.isalnum())
print(str1.title())
print(str1.isdigit())
print(str1.isupper())
print(str1.islower())
print(str1.find("name"))

